/**
 * convert.js — Build script to auto-generate cursor/ from claude/
 *
 * Run: node src/convert.js  (or: npm run build:cursor)
 *
 * Conversions:
 *   claude/rules/*.md       → cursor/rules/*.mdc  (YAML frontmatter injected)
 *   claude/skills/<n>/SKILL.md → cursor/skills/<i>/SKILL.md  (numbered, script note added)
 *
 * cursor/ is NEVER edited manually — always regenerated by this script.
 *
 * Skills with references/ subdirectory: reference files are inlined into the
 * Cursor SKILL.md so Cursor can access the full workflow without file loading.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const PACKAGE_ROOT = path.join(__dirname, '..');
const CLAUDE_DIR = path.join(PACKAGE_ROOT, 'claude');
const CURSOR_DIR = path.join(PACKAGE_ROOT, 'cursor');

// ─── Frontmatter config per rule file ────────────────────────────────────────
// alwaysApply: true  → injected into every Cursor prompt
// alwaysApply: false → Cursor AI decides based on description relevance
const RULE_CONFIG = {
  'development-rules.md': {
    alwaysApply: true,
    globs: '',
    description: 'Core development rules: YAGNI, KISS, DRY, file naming, code quality, and implementation standards.',
  },
  'primary-workflow.md': {
    alwaysApply: true,
    globs: '',
    description: 'Primary implementation workflow: planning, testing, code review, integration, debugging, and visual explanations.',
  },
  'documentation-management.md': {
    alwaysApply: false,
    globs: 'docs/**',
    description: 'Documentation management: roadmap, changelog, plan structure, and update protocols.',
  },
  'orchestration-protocol.md': {
    alwaysApply: false,
    globs: '',
    description: 'Subagent orchestration: delegation context, sequential chaining, and parallel execution patterns.',
  },
  'team-coordination-rules.md': {
    alwaysApply: false,
    globs: '',
    description: 'Team coordination rules for multi-agent sessions: file ownership, git safety, communication protocol.',
  },
};

// ─── Patterns that indicate script execution sections in SKILL.md ─────────────
const SCRIPT_PATTERNS = [
  /```(?:bash|shell|sh|python|py)\b/i,
  /\.claude\/skills\/.+\/scripts\//,
  /\.venv\/bin\//,
  /install\.sh/,
  /install\.ps1/,
];

/**
 * Check if SKILL.md content references script execution.
 */
function hasScriptContent(content) {
  return SCRIPT_PATTERNS.some((pattern) => pattern.test(content));
}

/**
 * Convert claude/rules/*.md → cursor/rules/*.mdc
 * Injects YAML frontmatter block before existing content.
 */
function convertRules() {
  const rulesDir = path.join(CLAUDE_DIR, 'rules');
  const outDir = path.join(CURSOR_DIR, 'rules');
  fs.mkdirSync(outDir, { recursive: true });

  const files = fs.readdirSync(rulesDir).filter((f) => f.endsWith('.md'));

  for (const filename of files) {
    const config = RULE_CONFIG[filename];
    if (!config) {
      console.warn(`  ⚠ No RULE_CONFIG for ${filename} — skipping`);
      continue;
    }

    const content = fs.readFileSync(path.join(rulesDir, filename), 'utf8');
    const baseName = filename.replace(/\.md$/, '');

    // Build YAML frontmatter
    const globsLine = config.globs ? `\nglobs: "${config.globs}"` : '';
    const frontmatter = `---\ndescription: ${config.description}${globsLine}\nalwaysApply: ${config.alwaysApply}\n---\n\n`;

    const outPath = path.join(outDir, `${baseName}.mdc`);
    fs.writeFileSync(outPath, frontmatter + content, 'utf8');
    console.log(`  ✓ rules/${baseName}.mdc`);
  }
}

/**
 * Convert claude/skills/<name>/SKILL.md → cursor/skills/<name>/SKILL.md
 * Preserves skill names as folder names so Cursor can identify skills by name.
 * Appends a note if script execution content is detected.
 */
function convertSkills(skillDirs) {
  const skillsDir = path.join(CLAUDE_DIR, 'skills');
  const outSkillsDir = path.join(CURSOR_DIR, 'skills');
  fs.mkdirSync(outSkillsDir, { recursive: true });

  skillDirs.forEach((skillName) => {
    const skillDir = path.join(skillsDir, skillName);
    const srcPath = path.join(skillDir, 'SKILL.md');
    let content = fs.readFileSync(srcPath, 'utf8');

    // Replace `references/<file>.md` load instructions with inline note since refs are embedded below.
    content = content.replace(
      /→ Load `references\/([^`]+\.md)`/g,
      '→ Follow the "$1" section below under **Reference Workflows**'
    );

    // Inline references/ files so Cursor has full workflow without file loading.
    // Claude Code loads these dynamically; Cursor needs them embedded.
    const refsDir = path.join(skillDir, 'references');
    if (fs.existsSync(refsDir)) {
      const refFiles = fs.readdirSync(refsDir)
        .filter((f) => f.endsWith('.md'))
        .sort();

      if (refFiles.length > 0) {
        content += '\n\n---\n\n## Reference Workflows\n\n';
        content += '> The following sections are inlined from the skill\'s reference files for Cursor compatibility.\n\n';

        for (const refFile of refFiles) {
          const refContent = fs.readFileSync(path.join(refsDir, refFile), 'utf8');
          const refTitle = refFile.replace(/\.md$/, '').replace(/-/g, ' ');
          content += `### ${refTitle}\n\n${refContent}\n\n`;
        }
      }
    }

    // Replace Claude Code-specific $ARGUMENTS placeholder with Cursor-friendly instruction.
    // Must run AFTER references are inlined (refs may also contain $ARGUMENTS).
    // Claude Code injects $ARGUMENTS at runtime; Cursor reads the user's message directly.
    content = content.replace(/\$ARGUMENTS/g, 'the user\'s message (text after the skill name)');

    // Cursor has no Task tool / agent spawning. Replace spawn instructions with direct execution.
    // Patterns: "spawn X agent via Task tool", "You MUST spawn X agent", "delegate to X agent"
    content = content.replace(
      /You MUST spawn [`\w-]+ agent via Task tool[^\n]*/gi,
      'You (Cursor AI) must do this directly — no agent spawning available.'
    );
    content = content.replace(
      /\*\*CRITICAL:\*\* You MUST spawn [`\w-]+ agent[^\n]*/gi,
      '**Do this directly** — Cursor does not support agent spawning.'
    );
    content = content.replace(
      /spawn [`'\w-]+ agent[s]? via Task tool/gi,
      'perform this step directly'
    );
    content = content.replace(
      /delegate to [`'\w-]+ agent/gi,
      'do this directly'
    );
    content = content.replace(
      /via Task tool/gi,
      'directly'
    );
    content = content.replace(
      /\*\*You \(main agent\) must spawn readers\*\*[^\n]*/gi,
      '**Read all docs files directly** — no parallel agents available in Cursor.'
    );
    content = content.replace(
      /Spawn \d[-–]\d+ `\w+` agents?[^\n]*/gi,
      'Read all files directly.'
    );
    content = content.replace(
      /spawn \d[-–]\d+ `\w+` agents?/gi,
      'read them directly'
    );
    // Replace "Activate ck:X skill" with Cursor @-reference equivalent
    content = content.replace(
      /Activate `(ck:[\w-]+)` skill/gi,
      (_, skillRef) => {
        const skillName = skillRef.replace('ck:', '');
        return `Follow \`@.cursor/skills/${skillName}/SKILL.md\``;
      }
    );

    // Append Claude-only note if skill references scripts
    if (hasScriptContent(content)) {
      content +=
        '\n\n> **Note (Cursor):** Script execution sections in this skill are Claude Code only. ' +
        'Cursor uses the instructions above. Run `.claude/skills/install.sh` in Claude Code to enable full capabilities.\n';
    }

    const outDir = path.join(outSkillsDir, skillName);
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(path.join(outDir, 'SKILL.md'), content, 'utf8');
  });

  console.log(`  ✓ ${skillDirs.length} skills converted → cursor/skills/`);
}

/**
 * Generate cursor/rules/skills-catalog.mdc — a single always-applied rule that
 * lists all available skills so Cursor AI knows they exist and how to invoke them.
 * User says "use cook skill" → Cursor reads catalog → references .cursor/skills/cook/SKILL.md
 */
function generateSkillsCatalog(skillDirs) {
  const rulesDir = path.join(CURSOR_DIR, 'rules');
  fs.mkdirSync(rulesDir, { recursive: true });

  const skillsDir = path.join(CLAUDE_DIR, 'skills');

  // Build catalog rows: name | description | path
  const rows = skillDirs.map((skillName) => {
    const content = fs.readFileSync(path.join(skillsDir, skillName, 'SKILL.md'), 'utf8');
    // Match quoted, unquoted, or YAML block scalar (>-) description in frontmatter
    const quoted = content.match(/^description:\s*"(.+?)"\s*$/m);
    const unquoted = content.match(/^description:\s*([^"\n>|][^\n]+)\s*$/m);
    const blockScalar = content.match(/^description:\s*>-?\s*\n\s+(.+)/m);
    let desc = skillName;
    if (quoted) desc = quoted[1];
    else if (blockScalar) desc = blockScalar[1].trim(); // check before unquoted (>- prefix)
    else if (unquoted) desc = unquoted[1].trim();
    // Truncate to 80 chars to keep table readable
    if (desc.length > 80) desc = desc.slice(0, 77) + '...';
    return `| \`${skillName}\` | ${desc} | \`.cursor/skills/${skillName}/SKILL.md\` |`;
  });

  const catalog = `---
description: Skills catalog — lists all available agent workflows and how to invoke them.
alwaysApply: true
---

# Available Skills

When the user asks to perform a task that matches a skill below, read the skill's SKILL.md file and follow its workflow.

**How to invoke:** Reference the skill file directly, e.g. \`@.cursor/skills/cook/SKILL.md\`

| Skill | Description | File |
|-------|-------------|------|
${rows.join('\n')}

## Usage Examples

- "use cook skill to implement login" → read \`@.cursor/skills/cook/SKILL.md\`
- "run docs init" → read \`@.cursor/skills/docs/SKILL.md\`, follow init workflow
- "brainstorm authentication options" → read \`@.cursor/skills/brainstorm/SKILL.md\`
- "fix this bug" → read \`@.cursor/skills/fix/SKILL.md\`
- "plan this feature" → read \`@.cursor/skills/plan/SKILL.md\`
`;

  fs.writeFileSync(path.join(rulesDir, 'skills-catalog.mdc'), catalog, 'utf8');
  console.log('  ✓ rules/skills-catalog.mdc');
}

/**
 * Convert claude/agents/*.md → cursor/rules/agent-<name>.mdc
 *
 * Cursor has no .cursor/agents/ concept — agents are prompt-based personas.
 * We expose each agent as an on-demand rule (alwaysApply: false) so Cursor
 * loads its persona/instructions when the user explicitly references it.
 *
 * Frontmatter is extracted from the Claude agent's YAML frontmatter:
 *   name, description → used to build the MDC header.
 *   model, tools, memory → stripped (Claude Code only).
 */
function convertAgents() {
  const agentsDir = path.join(CLAUDE_DIR, 'agents');
  if (!fs.existsSync(agentsDir)) return;

  const outDir = path.join(CURSOR_DIR, 'rules');
  fs.mkdirSync(outDir, { recursive: true });

  const files = fs.readdirSync(agentsDir).filter((f) => f.endsWith('.md'));

  for (const filename of files) {
    const raw = fs.readFileSync(path.join(agentsDir, filename), 'utf8');
    const baseName = filename.replace(/\.md$/, '');

    // Extract description from Claude agent frontmatter
    const descMatch = raw.match(/^description:\s*'([\s\S]+?)'\s*$/m)
      || raw.match(/^description:\s*"([\s\S]+?)"\s*$/m)
      || raw.match(/^description:\s*([^\n'"]+)\s*$/m);
    const description = descMatch
      ? descMatch[1].replace(/\s+/g, ' ').trim().slice(0, 120)
      : `${baseName} agent persona and instructions`;

    // Strip YAML frontmatter block (---...---) from agent content
    const body = raw.replace(/^---[\s\S]*?---\n/, '').trimStart();

    // Apply same Cursor-compatibility transforms as skills
    let content = body;
    content = content.replace(/\$ARGUMENTS/g, 'the user\'s message');
    content = content.replace(/via Task tool/gi, 'directly');
    content = content.replace(/delegate to [`'\w-]+ agent/gi, 'do this directly');

    const frontmatter = `---\ndescription: "${description}"\nalwaysApply: false\n---\n\n`;
    // Add agent identity header so Cursor knows what persona to adopt
    const header = `> **Agent: ${baseName}** — When this rule is active, adopt this agent's role and follow its instructions.\n\n`;

    const outPath = path.join(outDir, `agent-${baseName}.mdc`);
    fs.writeFileSync(outPath, frontmatter + header + content, 'utf8');
  }

  console.log(`  ✓ ${files.length} agents converted → cursor/rules/agent-*.mdc`);
}

/**
 * Main entry — wipes cursor/ and regenerates from claude/
 */
function buildCursorTemplates() {
  console.log('Building cursor/ from claude/...');

  // Wipe and recreate cursor/
  fs.rmSync(CURSOR_DIR, { recursive: true, force: true });
  fs.mkdirSync(CURSOR_DIR, { recursive: true });

  console.log('Converting rules...');
  convertRules();

  console.log('Converting agents...');
  convertAgents();

  console.log('Converting skills...');
  // Collect skill dirs here so we can reuse for catalog generation
  const skillsDir = path.join(CLAUDE_DIR, 'skills');
  const skillDirs = fs
    .readdirSync(skillsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((name) => fs.existsSync(path.join(skillsDir, name, 'SKILL.md')))
    .sort();

  convertSkills(skillDirs);

  console.log('Generating skills catalog...');
  generateSkillsCatalog(skillDirs);

  console.log('\n✓ cursor/ generated successfully');
}

buildCursorTemplates();
