/**
 * convert.js — Build script to auto-generate cursor/ from claude/
 *
 * Run: node src/convert.js  (or: npm run build:cursor)
 *
 * Conversions:
 *   claude/rules/*.md       → cursor/rules/*.mdc  (YAML frontmatter injected)
 *   claude/skills/<n>/SKILL.md → cursor/skills/<i>/SKILL.md  (numbered, script note added)
 *
 * cursor/ is NEVER edited manually — always regenerated by this script.
 *
 * Skills with references/ subdirectory: reference files are inlined into the
 * Cursor SKILL.md so Cursor can access the full workflow without file loading.
 */

'use strict';

const fs = require('fs');
const path = require('path');

const PACKAGE_ROOT = path.join(__dirname, '..');
const CLAUDE_DIR = path.join(PACKAGE_ROOT, 'claude');
const CURSOR_DIR = path.join(PACKAGE_ROOT, 'cursor');

// ─── Frontmatter config per rule file ────────────────────────────────────────
// alwaysApply: true  → injected into every Cursor prompt
// alwaysApply: false → Cursor AI decides based on description relevance
const RULE_CONFIG = {
  'development-rules.md': {
    alwaysApply: true,
    globs: '',
    description: 'Core development rules: YAGNI, KISS, DRY, file naming, code quality, and implementation standards.',
  },
  'primary-workflow.md': {
    alwaysApply: true,
    globs: '',
    description: 'Primary implementation workflow: planning, testing, code review, integration, debugging, and visual explanations.',
  },
  'documentation-management.md': {
    alwaysApply: false,
    globs: 'docs/**',
    description: 'Documentation management: roadmap, changelog, plan structure, and update protocols.',
  },
  'orchestration-protocol.md': {
    alwaysApply: false,
    globs: '',
    description: 'Subagent orchestration: delegation context, sequential chaining, and parallel execution patterns.',
  },
  'team-coordination-rules.md': {
    alwaysApply: false,
    globs: '',
    description: 'Team coordination rules for multi-agent sessions: file ownership, git safety, communication protocol.',
  },
};

// ─── Patterns that indicate script execution sections in SKILL.md ─────────────
const SCRIPT_PATTERNS = [
  /```(?:bash|shell|sh|python|py)\b/i,
  /\.claude\/skills\/.+\/scripts\//,
  /\.venv\/bin\//,
  /install\.sh/,
  /install\.ps1/,
];

/**
 * Check if SKILL.md content references script execution.
 */
function hasScriptContent(content) {
  return SCRIPT_PATTERNS.some((pattern) => pattern.test(content));
}

/**
 * Convert claude/rules/*.md → cursor/rules/*.mdc
 * Injects YAML frontmatter block before existing content.
 */
function convertRules() {
  const rulesDir = path.join(CLAUDE_DIR, 'rules');
  const outDir = path.join(CURSOR_DIR, 'rules');
  fs.mkdirSync(outDir, { recursive: true });

  const files = fs.readdirSync(rulesDir).filter((f) => f.endsWith('.md'));

  for (const filename of files) {
    const config = RULE_CONFIG[filename];
    if (!config) {
      console.warn(`  ⚠ No RULE_CONFIG for ${filename} — skipping`);
      continue;
    }

    const content = fs.readFileSync(path.join(rulesDir, filename), 'utf8');
    const baseName = filename.replace(/\.md$/, '');

    // Build YAML frontmatter
    const globsLine = config.globs ? `\nglobs: "${config.globs}"` : '';
    const frontmatter = `---\ndescription: ${config.description}${globsLine}\nalwaysApply: ${config.alwaysApply}\n---\n\n`;

    const outPath = path.join(outDir, `${baseName}.mdc`);
    fs.writeFileSync(outPath, frontmatter + content, 'utf8');
    console.log(`  ✓ rules/${baseName}.mdc`);
  }
}

/**
 * Convert claude/skills/<name>/SKILL.md → cursor/skills/<name>/SKILL.md
 * Preserves skill names as folder names so Cursor can identify skills by name.
 * Appends a note if script execution content is detected.
 */
function convertSkills() {
  const skillsDir = path.join(CLAUDE_DIR, 'skills');
  const outSkillsDir = path.join(CURSOR_DIR, 'skills');
  fs.mkdirSync(outSkillsDir, { recursive: true });

  // Collect skill dirs that have a SKILL.md
  const skillDirs = fs
    .readdirSync(skillsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((name) => fs.existsSync(path.join(skillsDir, name, 'SKILL.md')))
    .sort();

  skillDirs.forEach((skillName) => {
    const skillDir = path.join(skillsDir, skillName);
    const srcPath = path.join(skillDir, 'SKILL.md');
    let content = fs.readFileSync(srcPath, 'utf8');

    // Inline references/ files so Cursor has full workflow without file loading.
    // Claude Code loads these dynamically; Cursor needs them embedded.
    const refsDir = path.join(skillDir, 'references');
    if (fs.existsSync(refsDir)) {
      const refFiles = fs.readdirSync(refsDir)
        .filter((f) => f.endsWith('.md'))
        .sort();

      if (refFiles.length > 0) {
        content += '\n\n---\n\n## Reference Workflows\n\n';
        content += '> The following sections are inlined from the skill\'s reference files for Cursor compatibility.\n\n';

        for (const refFile of refFiles) {
          const refContent = fs.readFileSync(path.join(refsDir, refFile), 'utf8');
          const refTitle = refFile.replace(/\.md$/, '').replace(/-/g, ' ');
          content += `### ${refTitle}\n\n${refContent}\n\n`;
        }
      }
    }

    // Append Claude-only note if skill references scripts
    if (hasScriptContent(content)) {
      content +=
        '\n\n> **Note (Cursor):** Script execution sections in this skill are Claude Code only. ' +
        'Cursor uses the instructions above. Run `.claude/skills/install.sh` in Claude Code to enable full capabilities.\n';
    }

    const outDir = path.join(outSkillsDir, skillName);
    fs.mkdirSync(outDir, { recursive: true });
    fs.writeFileSync(path.join(outDir, 'SKILL.md'), content, 'utf8');
  });

  console.log(`  ✓ ${skillDirs.length} skills converted → cursor/skills/`);
}

/**
 * Main entry — wipes cursor/ and regenerates from claude/
 */
function buildCursorTemplates() {
  console.log('Building cursor/ from claude/...');

  // Wipe and recreate cursor/
  fs.rmSync(CURSOR_DIR, { recursive: true, force: true });
  fs.mkdirSync(CURSOR_DIR, { recursive: true });

  console.log('Converting rules...');
  convertRules();

  console.log('Converting skills...');
  convertSkills();

  console.log('\n✓ cursor/ generated successfully');
}

buildCursorTemplates();
